"""
advantage_direction_probe.py  (no training; needs the final checkpoints,
which are regenerated by run_s2d_study.py — only easy/sparse_seed0 is tracked).

Usage (repo root):
    python diagnostics/advantage_direction_probe.py easy sparse,bsrs_c_e1 0,1,2,3,4

Does the "R^{γλ} ≈ 0 ⇒ A' ≈ (1+η)A (a pure rescaling)" premise hold once the
hard task's −10 collision penalty is counted?

For each final checkpoint, collect one 2048-step STOCHASTIC rollout (as in
training) with shaping_mode="none", which yields raw rewards r, dones, and the
unshaped GAE advantages A from that checkpoint's own critic. The coupled
shaped advantages then follow from the verified identity
    A'_η = (1+η)·A − η·R^{γλ}
(tests_shaping.py T2, max error ~1e-15), so no second rollout is needed.

What the policy loss actually sees under normalize_advantage=True is the
normalized tensor, which is invariant to the (1+η) factor. So the decisive
quantity is corr(A'_η, A): if ≈ 1, normalization makes shaped and unshaped
policy gradients identical; the gap 1 − corr measures how far R^{γλ} breaks
the pure-rescaling premise.

Caveat: final-checkpoint policies are not the training-time policies; the
training-time evidence is progress.csv (Phase 3b).
"""
import copy
import os
import sys
import warnings
warnings.filterwarnings("ignore")
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import numpy as np
import torch as th
from stable_baselines3.common.vec_env import DummyVecEnv, VecNormalize

from arm_reach_env import ArmReachEnv
from ppo_shaped import ShapedPPO, discounted_reward_tail
from run_s2d_study import SuccessInfoWrapper, TASK_OBSTACLE, HP, run_dir

GAMMA, LAM, N = 0.99, 0.95, 2048
ETAS = (0.5, 1.0, 2.0)


def rollout(task, cond, seed):
    d = run_dir(task, cond, seed)
    env = DummyVecEnv([lambda: SuccessInfoWrapper(ArmReachEnv(
        render_mode=None, reward_mode="sparse", obstacle_mode=TASK_OBSTACLE[task]))])
    env = VecNormalize.load(f"{d}/vec_normalize.pkl", env)
    env.training = False
    env.norm_reward = False
    loaded = ShapedPPO.load(f"{d}/final_model", env=env)
    hp = {k: v for k, v in HP.items() if k != "verbose"}
    m = ShapedPPO("MlpPolicy", env, shaping_mode="none", eta=0.0, seed=seed,
                  verbose=0, **hp)
    m.policy.load_state_dict(copy.deepcopy(loaded.policy.state_dict()))
    # record collisions via a callback-free wrapper: re-read infos from the env
    coll = []
    orig_step = env.step_wait

    def step_wait():
        o, r, dn, infos = orig_step()
        coll.append(float(infos[0].get("collision", 0.0)))
        return o, r, dn, infos
    env.step_wait = step_wait
    _, cb = m._setup_learn(N)
    m.collect_rollouts(m.env, cb, m.rollout_buffer, N)
    dg = m._last_rollout_diag
    env.close()
    return dg["raw_rewards"][:, 0], dg["dones"][:, 0], dg["advantages"][:, 0], np.array(coll[:N])


def main(task, conds, seeds):
    print(f"\n=== {task} task: {N}-step stochastic rollout per final checkpoint ===")
    hdr = (f"{'cond/seed':<20}{'coll%':>7}{'succ%':>7}{'r≠0 %':>7}{'R≠0 %':>7}"
           + "".join(f"{'corr η='+str(e):>12}" for e in ETAS)
           + "".join(f"{'|ηR|/|(1+η)A| η='+str(e):>21}" for e in (1.0,)))
    print(hdr)
    agg = {e: [] for e in ETAS}
    for c in conds:
        for s in seeds:
            r, dn, A, coll = rollout(task, c, s)
            R = discounted_reward_tail(r.reshape(-1, 1), dn.reshape(-1, 1), GAMMA * LAM)[:, 0]
            row = f"{c+'/s'+str(s):<20}{100*coll.mean():>7.2f}{100*np.mean(r > 0):>7.2f}" \
                  f"{100*np.mean(r != 0):>7.2f}{100*np.mean(np.abs(R) > 1e-9):>7.2f}"
            for e in ETAS:
                Ap = (1 + e) * A - e * R
                cr = np.corrcoef(Ap, A)[0, 1]
                agg[e].append(cr)
                row += f"{cr:>12.6f}"
            row += f"{np.linalg.norm(1.0*R)/np.linalg.norm(2.0*A):>21.4f}"
            print(row, flush=True)
    print("  mean corr over all rows: " + "  ".join(f"η={e}: {np.mean(agg[e]):.6f} (min {np.min(agg[e]):.6f})" for e in ETAS))


if __name__ == "__main__":
    task = sys.argv[1]
    conds = sys.argv[2].split(",")
    seeds = [int(x) for x in sys.argv[3].split(",")]
    main(task, conds, seeds)
